---
title: Some news is good news
author: Jai
date: '2020-07-23'
slug: some-news-is-good-news
categories:
  - Public Health
tags:
  - Coronavirus
description: ''
thumbnail: ''
---

---
title: Some news is good news
author: Jai
date: '2020-07-23'
slug: some-news-is-good-news
categories:
  - Public Health
tags: [Coronavirus]
description: ''
thumbnail: ''
---

I surveyed friends on Facebook a while back asking what they hoped the results would be if they got a SARS-CoV-2 antibody test. They gave a range of answers. Some hoped for positive results, others negative.

This question has scaled up. Seroprevalence is 6-24 times higher than indicated by reported cases.

[Seroprevalence of Antibodies to SARS-CoV-2 in 10 Sites in the United States, March 23-May 12, 2020](https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2768834)

I see some news outlets reporting this in dire tones. Yet, it is good news! I would hope for positive results from an antibody test for myself and high seroprevalence from a serological survey. High seroprevalence means a lot more people than we thought got through exposure to coronavirus and they're fine. That's great. Naturally, the revelation of many previously undetected exposures doesn't help the people hit hard by COVID-19 already, but that number didn't change with the new discovery.

If I'm in the company of two other people, either of them could potentially transmit coronavirus to me. If now seroprevalence turned out to be, say 33% just for illustration, and given I'm not positive yet myself, then probably one of the other two has antibodies and only one of the two others is likely to be able to infect me now. In this scenario, the revelation of high seroprevalence just dropped the risk of me contracting COVID-19 by half.

That is good news.

I always appreciate the words of epidemiologist Dr. David Katz, from his op-eds in the *New York Times* to his interviews. Here is his take on seroprevalence reports and interpreting the news.

<iframe width="560" height="315" src="https://www.youtube.com/embed/CFSk_meafYY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
https://youtu.be/CFSk_meafYY