---
title: Conversation with Dr. Robert Redfield, MD
author: Jai
date: '2020-07-25'
slug: conversation-with-dr-robert-redfield-md
categories:
  - Public Health
tags:
  - Coronavirus
description: ''
thumbnail: ''
---

I see CDC Director, Dr. Robert R. Redfield, MD all the time on the news and appearing before Congress. The interview below is a live stream from July 14, 2020. Seeing Dr. Redfield in a loosened up environment in conversation with a colleague revealed a lot more of him. I learned about his background, his experience, and who he is as a man. It solidified my respect.

In his interview, Dr. Redfield shares very interesting perspectives about the mission of the Centers for Disease Control and Prevention, about the role of public service, and about leadership. I learned a lot and I especially enjoyed getting to know him a little better.

The interviewer is Dr. Howard Bauchner, the editor-in-chief of the *Journal of the American Medical Association*. I subscribe to the JAMA Network on YouTube, so I can view his series of interviews, called "Conversations with Dr. Bauchner," that illuminate health topics for a wide audience.

The JAMA Network is a collection of 12 international peer-reviewed medical journals that features the best in research, reviews, and commentary across the spectrum of medical and surgical practice. Led by the flagship journal JAMA®, the JAMA Network's mission is to improve the public health by providing the information that matters most to practitioners and researchers.

Here are the topics from the interview with Dr. Redfield:

- 0:00 Introduction
- 0:20 Background on Dr Redfield
- 2:18 Universal masking
- 5:27 Politics and masks
- 7:11 What will the next few weeks look like?
- 11:40 Vaccines for COVID-19
- 14:26 Bridging therapies (Monoclonal Antibodies / Immunoglobulins)
- 19:37 Criticism of the CDC for its handling of COVID-19
- 26:26 What's driving the surge in the South
- 27:26 What can we do better to make sure the message is better accepted by Americans?
- 29:09 Contract tracing and surveillance strategies
- 34:50 Testifying before Congress

<iframe width="560" height="315" src="https://www.youtube.com/embed/jzHIhSZ_fiA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>